### ISSUE TITLE
Предложения по дизайну

### ISSUE THREAD

**Issue by dorohovGeorge** [dorohovGeorge/2d-game#4]
Необходимо представить примерное дизайнерское решение по основным сущностям и локациям.
Например, главный герой, пару врагов и возможно первая локация, основные предметы (сундук, зелья, может одно два оружия). Основной стиль пиксель-арт.

**Comment by dorohovGeorge** [comment]
Прошу также уделить время дизайну интерфейса по возможности.

**Comment by klyuukva** [comment]
В ходе работы я уделила внимание дизайну игры. Продумала, как будут выглядеть основные мобы и окружающее пространство
